---
title: ""
output: 
  html_document:
    self_contained: true
date: ""
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
turnout_income <- readRDS("~/Desktop/final-project-Smlfberry/data/turnout_income.rds")
il_counties <- readRDS("data/il_counties.rds")
il_counties_pct <- readRDS("data/il_counties_pct.rds")

il_counties_pct_sf <- il_counties %>%
  left_join(st_drop_geometry(il_counties_pct), by = "GEOID") %>%
  mutate(pct_college = pct_bachelors + pct_grad)
```

```{r join data, echo=FALSE, message=FALSE, warning=FALSE}
il_combined <- il_counties_pct_sf %>%
  left_join(st_drop_geometry(turnout_income %>% filter(state == "IL")), 
            by = c("GEOID" = "geoid")) %>%
  mutate(
    pct_college = pct_bachelors + pct_grad,
    low_income = median_income < quantile(median_income, 0.25, na.rm = TRUE),
    low_edu = pct_college < 18,
    category = case_when(
      low_income & low_edu ~ "Both",
      low_income & !low_edu ~ "Low income only",
      !low_income & low_edu ~ "Low education only",
      TRUE ~ "Neither"
    )
  )
```


```{r css, echo=FALSE, results='asis'}

# make background consistent 

cat('<style>
  body { margin: 0; padding: 0; background: #faf9f6; }
  html { background: #faf9f6; }
  .leaflet-container { background: #faf9f6 !important; }
  .leaflet-control-zoom { display: none; }
</style>')
```

```{r map of educ and income, echo=FALSE, message=FALSE, warning=FALSE}
pal_combined <- colorFactor(
  palette = c(
    "Both" = "#264653",
    "Low income only" = "#2a9d8f",
    "Low education only" = "#e9c46a",
    "Neither" = "#d0cfc9"
  ),
  domain = il_combined$category
)
il_combined <- st_transform(il_combined, crs = 4326)
leaflet(il_combined, options = leafletOptions(scrollWheelZoom = FALSE)) %>%
  addPolygons(
    fillColor = ~pal_combined(category),
    fillOpacity = 0.8,
    color = "white",
    weight = 0.5,
    label = ~ifelse(category != "Neither",
                    paste0(county, ": ", category),
                    NA)
  ) %>%
  addLegend(
    pal = pal_combined,
    values = ~category,
    title = "County Profile",
    position = "bottomleft"
  ) %>%
  htmlwidgets::onRender("
    function(el, x) {
      el.style.background = '#faf9f6';
      el.querySelector('.leaflet-container').style.background = '#faf9f6';
      setTimeout(function() {
        var map = HTMLWidgets.find(el).getMap();
        map.invalidateSize();
        map.fitBounds([[36.9, -91.5], [42.5, -87.0]]);
      }, 300);
    }
  ")
```
